### ISSUE TITLE
Data balance unit

### ISSUE THREAD

**Issue by ivanrajkovic** [mbillow/ha-redpocket#2]
Hi, 
The number for data balance that RedPocket returns for me is in tens of kilobytes (or 1/100 MB) - 15192 for 151.92MB, but home assistant shows this as 15,192MB. Not sure if this is the same for all of the accounts/packages, maybe there can be a scaling option implemented.

**Comment by mbillow** [comment]
This is _super_ interesting. It definitely fits right in with the rest of the wonky bits of their API. I wonder how they are dealing with this and consistently displaying it on their own front end(s).

Are you willing to check some RP API responses for me? I’d love to figure out the “right” way to display this correctly before falling back to just implementing a configurable denominator.

**Comment by ivanrajkovic** [comment]
Sure, just send me API calls you need.

**Comment by mbillow** [comment]
- Login to your RP account
- Go to https://www.redpocket.com/account/get-other-lines
- Find your account hash in the JSON output under `confirmedLines`:
   - ![Markup on 2021-05-18 at 15:59:50](https://user-images.githubusercontent.com/8651166/118722720-1f4c6100-b7f2-11eb-880e-cb4000e876fe.png)
- Then navigate to https://www.redpocket.com/account/get-details?id={the-hash-from-above}
  - Make sure to remove any personal data from this response, but I would love to see what it returns for your account.
  - ![Markup on 2021-05-18 at 15:57:27](https://user-images.githubusercontent.com/8651166/118722888-53c01d00-b7f2-11eb-9082-a1c1ce3c4246.png)

**Comment by ivanrajkovic** [comment]
here is the info. I have quite small yearly plan, maybe that is why they are using xxx.xx MB number format. 
Let me know if you need anything else.

![redpocket](https://user-images.githubusercontent.com/19917903/118743666-9b9d6f00-b807-11eb-9bba-157c9be1fe70.png)

**Comment by mbillow** [comment]
Yup, that’s the issue. I am just stripping all non digits and casting the string to an int: https://github.com/mbillow/python-redpocket/blob/a083e9744dac10eb2952e9888870929a2b98d09b/redpocket/api.py#L60

I assumed it would always be an int with a comma that needed to be removed. I’ll handle decimals properly when I get a chance (this weekend at the latest). Thanks for the info!

**Comment by ivanrajkovic** [comment]
Thanks for looking into this.
Would something like this work:

float("".join(balance.split(',')))
or 
int(float("".join(balance.split(','))))
or
int("".join(balance.split(',')).split('.')[0])

it should remove the comma but keep the decimal point, or keep everything before the decimal point.
int should be sufficient since nobody really cares about fractions of MB.

**Comment by mbillow** [comment]
So, I wanted to stray away from manually parsing the value given that Python has some pretty decent locale string parsing built-ins. I ended up going with: 
```python
locale.setlocale(locale.LC_ALL, 'en_US.UTF-8')
locale.atof(balance)
```
Which will turn anything formatted in traditional en_US styles (1,000, 1000.32, 1000) to a proper `float`.

**Comment by mbillow** [comment]
You should be able to upgrade to v2.1.0 in HACS, restart HA, and this should be fixed. 😄

**Comment by ivanrajkovic** [comment]
Great, thanks.

**Comment by ivanrajkovic** [comment]
small warning: this will not work if the person doesn't have 'en_US.UTF-8' locale generated. Maybe you can add this as a requirement.

**Comment by mbillow** [comment]
Welp, never mind, it worked locally... but the version of Python in my production Docker instance did not like that. I guess we are going to go back to hacky string replacing and manual type coercion...

**Comment by mbillow** [comment]
I pushed a new version of `python-redpocket` that uses `float(balance.replace(",", ""))` to get around the comma breaking the normal `str=>float` type coercion.

**Comment by ivanrajkovic** [comment]
Sounds good. 
One thing I noticed is that now voice and messaging balances are also float and they show with one decimal place, which doesn't make too much sense.

**Comment by mbillow** [comment]
I changed the type hinting on all of the balances to `Union[int, float]` and added some logic in the sanitization function that gets called on them to return an `int` when decimal precision isn't necessary. Thanks for all your feedback. 😄
